[workspace]
resolver = "2"
members = [
    "packages/remod_core",
    "packages/remod_config",
    "packages/remod_cli",
    "packages/remod_code",
]
default-members = ["packages/remod_cli"]

[workspace.dependencies]
glob = { version = "0.3.1" }
