[package]
name = "remod_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
remod_config = { path = "../remod_config", version = "*" }
remod_core = { path = "../remod_core", version = "*" }
glob = { workspace = true }
